import os
import sys

PATH = '/home/san/Algorithms/Reference/ReferenceBook/'

content = os.popen('python ' + PATH + 'getContents.py').read()

with open(PATH + 'ReferenceTemplate.tex', 'r') as f:
    template = f.read()

template = template.replace('	% autogenerated code here', content)

with open(PATH + 'Reference.tex', 'w') as f:
    f.write(template)

opt = ""
if len(sys.argv) != 1: opt = sys.argv[1]

os.system('ltx ' + PATH + 'Reference.tex ' + opt)
